package com.planit.smsrenta.modelos;
// Generated 02-mar-2016 12:47:17 by Hibernate Tools 4.3.1

/**
 * SmsCalificacion generated by hbm2java
 */
public class SmsCalificacion implements java.io.Serializable {

    private Integer idCalificacion;
    private SmsReservacion smsReservacion;
    private String calificacionObservacion;
    private Integer calificacionCalidadServicio;

    public SmsCalificacion() {
        calificacionCalidadServicio = 1;
    }

    public SmsCalificacion(SmsReservacion smsReservacion) {
        this.smsReservacion = smsReservacion;
    }

    public SmsCalificacion(SmsReservacion smsReservacion, String calificacionObservacion, Integer calificacionCalidadServicio) {
        this.smsReservacion = smsReservacion;
        this.calificacionObservacion = calificacionObservacion;
        this.calificacionCalidadServicio = calificacionCalidadServicio;
    }

    public Integer getIdCalificacion() {
        return idCalificacion;
    }

    public void setIdCalificacion(Integer idCalificacion) {
        this.idCalificacion = idCalificacion;
    }

    public SmsReservacion getSmsReservacion() {
        return smsReservacion;
    }

    public void setSmsReservacion(SmsReservacion smsReservacion) {
        this.smsReservacion = smsReservacion;
    }

    public String getCalificacionObservacion() {
        return calificacionObservacion;
    }

    public void setCalificacionObservacion(String calificacionObservacion) {
        this.calificacionObservacion = calificacionObservacion;
    }

    public Integer getCalificacionCalidadServicio() {
        return calificacionCalidadServicio;
    }

    public void setCalificacionCalidadServicio(Integer calificacionCalidadServicio) {
        this.calificacionCalidadServicio = calificacionCalidadServicio;
    }
}
