package com.planit.smsrenta.modelos;
// Generated 02-mar-2016 12:47:17 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * SmsEmpleado generated by hbm2java
 */
public class SmsEmpleado implements java.io.Serializable {

    private Integer idEmpleado;
    private SmsHojavida smsHojavida;
    private SmsProveedor smsProveedor;
    private SmsUsuario smsUsuario;
    private SmsEstado smsEstado;
    private Set<SmsCategoriasServicio> smsCategoriasServicios = new HashSet<>(0);
    private Set<SmsReservacion> smsReservacions = new HashSet<>(0);
    private Set<SmsVehiculo> smsVehiculos = new HashSet<>(0);

    public SmsEmpleado() {
        this.smsHojavida = new SmsHojavida();
        this.smsProveedor = new SmsProveedor();
        this.smsUsuario = new SmsUsuario();
        this.smsEstado = new SmsEstado();
    }

    public SmsEmpleado(SmsProveedor smsProveedor, SmsUsuario smsUsuario) {
        this.smsProveedor = smsProveedor;
        this.smsUsuario = smsUsuario;
    }

    public SmsEmpleado(SmsHojavida smsHojavida, SmsEstado smsEstado, SmsProveedor smsProveedor, SmsUsuario smsUsuario, Set<SmsCategoriasServicio> smsCategoriasServicios, Set<SmsReservacion> smsReservacions,Set<SmsVehiculo> smsVehiculos) {
        this.smsHojavida = smsHojavida;
        this.smsProveedor = smsProveedor;
        this.smsUsuario = smsUsuario;
        this.smsEstado = smsEstado;
        this.smsCategoriasServicios = smsCategoriasServicios;
        this.smsReservacions = smsReservacions;
        this.smsVehiculos = smsVehiculos;
    }

    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }

    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }

    public SmsHojavida getSmsHojavida() {
        return this.smsHojavida;
    }

    public void setSmsHojavida(SmsHojavida smsHojavida) {
        this.smsHojavida = smsHojavida;
    }

    public SmsProveedor getSmsProveedor() {
        return this.smsProveedor;
    }

    public void setSmsProveedor(SmsProveedor smsProveedor) {
        this.smsProveedor = smsProveedor;
    }

    public SmsUsuario getSmsUsuario() {
        return this.smsUsuario;
    }

    public void setSmsUsuario(SmsUsuario smsUsuario) {
        this.smsUsuario = smsUsuario;
    }

    public Set<SmsCategoriasServicio> getSmsCategoriasServicios() {
        return this.smsCategoriasServicios;
    }

    public void setSmsCategoriasServicios(Set<SmsCategoriasServicio> smsCategoriasServicios) {
        this.smsCategoriasServicios = smsCategoriasServicios;
    }

    public Set<SmsReservacion> getSmsReservacions() {
        return this.smsReservacions;
    }

    public void setSmsReservacions(Set<SmsReservacion> smsReservacions) {
        this.smsReservacions = smsReservacions;
    }

    public SmsEstado getSmsEstado() {
        return smsEstado;
    }

    public void setSmsEstado(SmsEstado smsEstado) {
        this.smsEstado = smsEstado;
    }

    public Set<SmsVehiculo> getSmsVehiculos() {
        return smsVehiculos;
    }

    public void setSmsVehiculos(Set<SmsVehiculo> smsVehiculos) {
        this.smsVehiculos = smsVehiculos;
    }
    
    

    
}
