package com.planit.smsrenta.modelos;
// Generated 02-mar-2016 12:47:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SmsEstado generated by hbm2java
 */
public class SmsEstado  implements java.io.Serializable {


     private Integer idEstado;
     private String estadoNombre;
     private String estadoDescripcion;
     private Set<SmsReservacion> smsReservacions = new HashSet<>(0);
     private Set<SmsVehiculo> smsVehiculos = new HashSet<>(0);
     private Set<SmsEmpleado> smsEmpleados = new HashSet<>(0);

    public SmsEstado() {
    }
	
    public SmsEstado(String estadoNombre) {
        this.estadoNombre = estadoNombre;
    }
    public SmsEstado(String estadoNombre, String estadoDescripcion, Set<SmsReservacion> smsReservacions, Set<SmsEmpleado> smsEmpleados,  Set<SmsVehiculo> smsVehiculos) {
       this.estadoNombre = estadoNombre;
       this.estadoDescripcion = estadoDescripcion;
       this.smsReservacions = smsReservacions;
       this.smsVehiculos = smsVehiculos;
       this.smsEmpleados = smsEmpleados;
    }
   
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }
    public String getEstadoNombre() {
        return this.estadoNombre;
    }
    
    public void setEstadoNombre(String estadoNombre) {
        this.estadoNombre = estadoNombre;
    }
    public String getEstadoDescripcion() {
        return this.estadoDescripcion;
    }
    
    public void setEstadoDescripcion(String estadoDescripcion) {
        this.estadoDescripcion = estadoDescripcion;
    }
    public Set<SmsReservacion> getSmsReservacions() {
        return this.smsReservacions;
    }
    
    public void setSmsReservacions(Set<SmsReservacion> smsReservacions) {
        this.smsReservacions = smsReservacions;
    }

    public Set<SmsVehiculo> getSmsVehiculos() {
        return smsVehiculos;
    }

    public void setSmsVehiculos(Set<SmsVehiculo> smsVehiculos) {
        this.smsVehiculos = smsVehiculos;
    }

    public Set<SmsEmpleado> getSmsEmpleados() {
        return smsEmpleados;
    }

    public void setSmsEmpleados(Set<SmsEmpleado> smsEmpleados) {
        this.smsEmpleados = smsEmpleados;
    }

    



}


