package com.planit.smsrenta.modelos;
// Generated 02-mar-2016 12:47:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SmsPais generated by hbm2java
 */
public class SmsPais  implements java.io.Serializable {


     private Integer idPais;
     private String paisNombre;
     private Set<SmsDepartamento> smsDepartamentos = new HashSet<>(0);

    public SmsPais() {
    }

	
    public SmsPais(String paisNombre) {
        this.paisNombre = paisNombre;
    }
    public SmsPais(String paisNombre, Set<SmsDepartamento> smsDepartamentos) {
       this.paisNombre = paisNombre;
       this.smsDepartamentos = smsDepartamentos;
    }
   
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }
    public String getPaisNombre() {
        return this.paisNombre;
    }
    
    public void setPaisNombre(String paisNombre) {
        this.paisNombre = paisNombre;
    }
    public Set<SmsDepartamento> getSmsDepartamentos() {
        return this.smsDepartamentos;
    }
    
    public void setSmsDepartamentos(Set<SmsDepartamento> smsDepartamentos) {
        this.smsDepartamentos = smsDepartamentos;
    }




}


