package com.planit.smsrenta.modelos;
// Generated 02-mar-2016 12:47:17 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * SmsServicios generated by hbm2java
 */
public class SmsServicios implements java.io.Serializable {

    private Integer idServicio;
    private SmsCategoriasServicio smsCategoriasServicio;
    private SmsMercado smsMercado;
    private String servicioNombre;
    private String servicioDescripcion;
    private Integer servicioDuracion;
    private SmsTipoDuracion smsTipoDuracion;
    private Integer servicioConductor;
    private Set<SmsCostosservicios> smsCostosservicioses = new HashSet<>(0);
    private Set<SmsReservacion> smsReservacions = new HashSet<>(0);

    public SmsServicios() {
        this.smsCategoriasServicio = new SmsCategoriasServicio();
        this.smsMercado = new SmsMercado();
        this.servicioDuracion = 0;
    }

    public SmsServicios(SmsCategoriasServicio smsCategoriasServicio, String servicioNombre, int servicioDuracion, SmsMercado smsMercado, SmsTipoDuracion smsTipoDuracion) {
        this.smsCategoriasServicio = smsCategoriasServicio;
        this.servicioNombre = servicioNombre;
        this.servicioDuracion = servicioDuracion;
        this.smsMercado = smsMercado;
        this.smsTipoDuracion = smsTipoDuracion;
    }

    public SmsServicios(SmsCategoriasServicio smsCategoriasServicio, String servicioNombre, String servicioDescripcion, SmsTipoDuracion smsTipoDuracion, Set<SmsCostosservicios> smsCostosservicioses, Set<SmsReservacion> smsReservacions) {
        this.smsCategoriasServicio = smsCategoriasServicio;
        this.servicioNombre = servicioNombre;
        this.servicioDescripcion = servicioDescripcion;
        this.smsCostosservicioses = smsCostosservicioses;
        this.smsReservacions = smsReservacions;
        this.smsTipoDuracion = smsTipoDuracion;
    }

    public Integer getIdServicio() {
        return this.idServicio;
    }

    public void setIdServicio(Integer idServicio) {
        this.idServicio = idServicio;
    }

    public SmsCategoriasServicio getSmsCategoriasServicio() {
        return this.smsCategoriasServicio;
    }

    public void setSmsCategoriasServicio(SmsCategoriasServicio smsCategoriasServicio) {
        this.smsCategoriasServicio = smsCategoriasServicio;
    }

    public String getServicioNombre() {
        return this.servicioNombre;
    }

    public void setServicioNombre(String servicioNombre) {
        this.servicioNombre = servicioNombre;
    }

    public String getServicioDescripcion() {
        return this.servicioDescripcion;
    }

    public void setServicioDescripcion(String servicioDescripcion) {
        this.servicioDescripcion = servicioDescripcion;
    }

    public Set<SmsCostosservicios> getSmsCostosservicioses() {
        return this.smsCostosservicioses;
    }

    public void setSmsCostosservicioses(Set<SmsCostosservicios> smsCostosservicioses) {
        this.smsCostosservicioses = smsCostosservicioses;
    }

    public Set<SmsReservacion> getSmsReservacions() {
        return this.smsReservacions;
    }

    public void setSmsReservacions(Set<SmsReservacion> smsReservacions) {
        this.smsReservacions = smsReservacions;
    }

    public Integer getServicioDuracion() {
        return servicioDuracion;
    }

    public void setServicioDuracion(Integer servicioDuracion) {
        this.servicioDuracion = servicioDuracion;
    }

    public Integer getServicioConductor() {
        return servicioConductor;
    }

    public void setServicioConductor(Integer servicioConductor) {
        this.servicioConductor = servicioConductor;
    }

    public SmsMercado getSmsMercado() {
        return smsMercado;
    }

    public void setSmsMercado(SmsMercado smsMercado) {
        this.smsMercado = smsMercado;
    }

    public SmsTipoDuracion getSmsTipoDuracion() {
        return smsTipoDuracion;
    }

    public void setSmsTipoDuracion(SmsTipoDuracion smsTipoDuracion) {
        this.smsTipoDuracion = smsTipoDuracion;
    }

}
