
package ClienteTest;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VPOSWS20SOAP", targetNamespace = "http://www.alignet.com/VPOSWS20/", wsdlLocation = "https://testecommerce.credibanco.com/vpos2/services/VPOSWS20SOAP?wsdl")
public class VPOSWS20SOAP
    extends Service
{

    private final static URL VPOSWS20SOAP_WSDL_LOCATION;
    private final static WebServiceException VPOSWS20SOAP_EXCEPTION;
    private final static QName VPOSWS20SOAP_QNAME = new QName("http://www.alignet.com/VPOSWS20/", "VPOSWS20SOAP");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://testecommerce.credibanco.com/vpos2/services/VPOSWS20SOAP?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VPOSWS20SOAP_WSDL_LOCATION = url;
        VPOSWS20SOAP_EXCEPTION = e;
    }

    public VPOSWS20SOAP() {
        super(__getWsdlLocation(), VPOSWS20SOAP_QNAME);
    }

    public VPOSWS20SOAP(WebServiceFeature... features) {
        super(__getWsdlLocation(), VPOSWS20SOAP_QNAME, features);
    }

    public VPOSWS20SOAP(URL wsdlLocation) {
        super(wsdlLocation, VPOSWS20SOAP_QNAME);
    }

    public VPOSWS20SOAP(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VPOSWS20SOAP_QNAME, features);
    }

    public VPOSWS20SOAP(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VPOSWS20SOAP(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VPOSWS20
     */
    @WebEndpoint(name = "VPOSWS20SOAP")
    public VPOSWS20 getVPOSWS20SOAP() {
        return super.getPort(new QName("http://www.alignet.com/VPOSWS20/", "VPOSWS20SOAP"), VPOSWS20.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VPOSWS20
     */
    @WebEndpoint(name = "VPOSWS20SOAP")
    public VPOSWS20 getVPOSWS20SOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.alignet.com/VPOSWS20/", "VPOSWS20SOAP"), VPOSWS20.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VPOSWS20SOAP_EXCEPTION!= null) {
            throw VPOSWS20SOAP_EXCEPTION;
        }
        return VPOSWS20SOAP_WSDL_LOCATION;
    }

}
