package Modelo;
// Generated 23-feb-2016 11:25:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SmsCiudad generated by hbm2java
 */
public class SmsCiudad  implements java.io.Serializable {


     private Integer idCiudad;
     private SmsPais smsPais;
     private String ciudadNombre;
     private Set<SmsMunicipios> smsMunicipioses = new HashSet<SmsMunicipios>(0);
     private Set<SmsLugares> smsLugareses = new HashSet<SmsLugares>(0);
     private Set<SmsReservacion> smsReservacionsForIdCiudadDestino = new HashSet<SmsReservacion>(0);
     private Set<SmsVehiculo> smsVehiculos = new HashSet<SmsVehiculo>(0);
     private Set<SmsUsuario> smsUsuarios = new HashSet<SmsUsuario>(0);
     private Set<SmsReservacion> smsReservacionsForIdCiudadInicio = new HashSet<SmsReservacion>(0);

    public SmsCiudad() {
    }

	
    public SmsCiudad(SmsPais smsPais, String ciudadNombre) {
        this.smsPais = smsPais;
        this.ciudadNombre = ciudadNombre;
    }
    public SmsCiudad(SmsPais smsPais, String ciudadNombre, Set<SmsMunicipios> smsMunicipioses, Set<SmsLugares> smsLugareses, Set<SmsReservacion> smsReservacionsForIdCiudadDestino, Set<SmsVehiculo> smsVehiculos, Set<SmsUsuario> smsUsuarios, Set<SmsReservacion> smsReservacionsForIdCiudadInicio) {
       this.smsPais = smsPais;
       this.ciudadNombre = ciudadNombre;
       this.smsMunicipioses = smsMunicipioses;
       this.smsLugareses = smsLugareses;
       this.smsReservacionsForIdCiudadDestino = smsReservacionsForIdCiudadDestino;
       this.smsVehiculos = smsVehiculos;
       this.smsUsuarios = smsUsuarios;
       this.smsReservacionsForIdCiudadInicio = smsReservacionsForIdCiudadInicio;
    }
   
    public Integer getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(Integer idCiudad) {
        this.idCiudad = idCiudad;
    }
    public SmsPais getSmsPais() {
        return this.smsPais;
    }
    
    public void setSmsPais(SmsPais smsPais) {
        this.smsPais = smsPais;
    }
    public String getCiudadNombre() {
        return this.ciudadNombre;
    }
    
    public void setCiudadNombre(String ciudadNombre) {
        this.ciudadNombre = ciudadNombre;
    }
    public Set<SmsMunicipios> getSmsMunicipioses() {
        return this.smsMunicipioses;
    }
    
    public void setSmsMunicipioses(Set<SmsMunicipios> smsMunicipioses) {
        this.smsMunicipioses = smsMunicipioses;
    }
    public Set<SmsLugares> getSmsLugareses() {
        return this.smsLugareses;
    }
    
    public void setSmsLugareses(Set<SmsLugares> smsLugareses) {
        this.smsLugareses = smsLugareses;
    }
    public Set<SmsReservacion> getSmsReservacionsForIdCiudadDestino() {
        return this.smsReservacionsForIdCiudadDestino;
    }
    
    public void setSmsReservacionsForIdCiudadDestino(Set<SmsReservacion> smsReservacionsForIdCiudadDestino) {
        this.smsReservacionsForIdCiudadDestino = smsReservacionsForIdCiudadDestino;
    }
    public Set<SmsVehiculo> getSmsVehiculos() {
        return this.smsVehiculos;
    }
    
    public void setSmsVehiculos(Set<SmsVehiculo> smsVehiculos) {
        this.smsVehiculos = smsVehiculos;
    }
    public Set<SmsUsuario> getSmsUsuarios() {
        return this.smsUsuarios;
    }
    
    public void setSmsUsuarios(Set<SmsUsuario> smsUsuarios) {
        this.smsUsuarios = smsUsuarios;
    }
    public Set<SmsReservacion> getSmsReservacionsForIdCiudadInicio() {
        return this.smsReservacionsForIdCiudadInicio;
    }
    
    public void setSmsReservacionsForIdCiudadInicio(Set<SmsReservacion> smsReservacionsForIdCiudadInicio) {
        this.smsReservacionsForIdCiudadInicio = smsReservacionsForIdCiudadInicio;
    }




}


