package Modelo;
// Generated 23-feb-2016 11:25:04 by Hibernate Tools 4.3.1



/**
 * SmsCostosserviciosRenta generated by hbm2java
 */
public class SmsCostosserviciosRenta  implements java.io.Serializable {


     private Integer idCostosServRenta;
     private SmsServicios smsServicios;
     private SmsCategoria smsCategoria;
     private Integer costoServicioPrecio;

    public SmsCostosserviciosRenta() {
    }

    public SmsCostosserviciosRenta(SmsServicios smsServicios,SmsCategoria smsCategoria, int costoServicioPrecio) {
       this.smsServicios = smsServicios;
       this.smsCategoria = smsCategoria;
       this.costoServicioPrecio = costoServicioPrecio;
    }
   
    public Integer getIdCostosServRenta() {
        return this.idCostosServRenta;
    }
    
    public void setIdCostosServRenta(Integer idCostosServRenta) {
        this.idCostosServRenta = idCostosServRenta;
    }
    public SmsServicios getSmsServicios() {
        return this.smsServicios;
    }
    
    public void setSmsServicios(SmsServicios smsServicios) {
        this.smsServicios = smsServicios;
    }
    public int getCostoServicioPrecio() {
        return this.costoServicioPrecio;
    }
    
    public void setCostoServicioPrecio(int costoServicioPrecio) {
        this.costoServicioPrecio = costoServicioPrecio;
    }

    public SmsCategoria getSmsCategoria() {
        return smsCategoria;
    }

    public void setSmsCategoria(SmsCategoria smsCategoria) {
        this.smsCategoria = smsCategoria;
    }
    
    




}


