package Modelo;
// Generated 23-feb-2016 11:25:04 by Hibernate Tools 4.3.1



/**
 * SmsCostosserviciosRenta generated by hbm2java
 */
public class SmsCostosserviciosRenta  implements java.io.Serializable {


     private Integer idCostosServRenta;
     private SmsServicios smsServicios;
     private String costoServicioPrecio;

    public SmsCostosserviciosRenta() {
    }

    public SmsCostosserviciosRenta(SmsServicios smsServicios, String costoServicioPrecio) {
       this.smsServicios = smsServicios;
       this.costoServicioPrecio = costoServicioPrecio;
    }
   
    public Integer getIdCostosServRenta() {
        return this.idCostosServRenta;
    }
    
    public void setIdCostosServRenta(Integer idCostosServRenta) {
        this.idCostosServRenta = idCostosServRenta;
    }
    public SmsServicios getSmsServicios() {
        return this.smsServicios;
    }
    
    public void setSmsServicios(SmsServicios smsServicios) {
        this.smsServicios = smsServicios;
    }
    public String getCostoServicioPrecio() {
        return this.costoServicioPrecio;
    }
    
    public void setCostoServicioPrecio(String costoServicioPrecio) {
        this.costoServicioPrecio = costoServicioPrecio;
    }




}


