package Modelo;
// Generated 23-feb-2016 11:25:04 by Hibernate Tools 4.3.1



/**
 * SmsCostoserviciosTraslado generated by hbm2java
 */
public class SmsCostoserviciosTraslado  implements java.io.Serializable {


     private Integer idCostoServTraslado;
     private SmsServicios smsServicios;
     private int costoServicioPrecio;

    public SmsCostoserviciosTraslado() {
    }

    public SmsCostoserviciosTraslado(SmsServicios smsServicios, int costoServicioPrecio) {
       this.smsServicios = smsServicios;
       this.costoServicioPrecio = costoServicioPrecio;
    }
   
    public Integer getIdCostoServTraslado() {
        return this.idCostoServTraslado;
    }
    
    public void setIdCostoServTraslado(Integer idCostoServTraslado) {
        this.idCostoServTraslado = idCostoServTraslado;
    }
    public SmsServicios getSmsServicios() {
        return this.smsServicios;
    }
    
    public void setSmsServicios(SmsServicios smsServicios) {
        this.smsServicios = smsServicios;
    }
    public int getCostoServicioPrecio() {
        return this.costoServicioPrecio;
    }
    
    public void setCostoServicioPrecio(int costoServicioPrecio) {
        this.costoServicioPrecio = costoServicioPrecio;
    }




}


