package Modelo;
// Generated 02-mar-2016 12:47:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SmsCategoriasServicio generated by hbm2java
 */
public class SmsCategoriasServicio  implements java.io.Serializable {


     private Integer idCategoriaServicio;
     private String catNombre;
     private String catDescripcion;
     private SmsMercado smsMercado;
     private Set<SmsServicios> smsServicioses = new HashSet<>(0);
     private Set<SmsEmpleado> smsEmpleados = new HashSet<>(0);
     private Set<SmsVehiculo> smsVehiculos = new HashSet<>(0);
     private Set<SmsReservacion> smsReservacions = new HashSet<>(0);
     private Set<SmsLugares> smsLugares = new HashSet<>(0);

    public SmsCategoriasServicio() {
    this.smsMercado = new SmsMercado();
    }

	
    public SmsCategoriasServicio(String catNombre, SmsMercado smsMercado) {
        this.smsMercado = smsMercado;
        this.catNombre = catNombre;
    }
    
    public SmsCategoriasServicio(String catNombre, String catDescripcion, Set<SmsServicios> smsServicioses, Set<SmsEmpleado> smsEmpleados, Set<SmsVehiculo> smsVehiculos, Set<SmsReservacion> smsReservacions, Set<SmsLugares> smsLugares) {
       this.catNombre = catNombre;
       this.catDescripcion = catDescripcion;
       this.smsServicioses = smsServicioses;
       this.smsEmpleados = smsEmpleados;
       this.smsVehiculos = smsVehiculos;
       this.smsReservacions = smsReservacions;
       this.smsLugares = smsLugares;
    }
   
    public Integer getIdCategoriaServicio() {
        return this.idCategoriaServicio;
    }
    
    public void setIdCategoriaServicio(Integer idCategoriaServicio) {
        this.idCategoriaServicio = idCategoriaServicio;
    }
    public String getCatNombre() {
        return this.catNombre;
    }
    
    public void setCatNombre(String catNombre) {
        this.catNombre = catNombre;
    }
    public String getCatDescripcion() {
        return this.catDescripcion;
    }
    
    public void setCatDescripcion(String catDescripcion) {
        this.catDescripcion = catDescripcion;
    }
    public Set<SmsServicios> getSmsServicioses() {
        return this.smsServicioses;
    }
    
    public void setSmsServicioses(Set<SmsServicios> smsServicioses) {
        this.smsServicioses = smsServicioses;
    }
    public Set<SmsEmpleado> getSmsEmpleados() {
        return this.smsEmpleados;
    }
    
    public void setSmsEmpleados(Set<SmsEmpleado> smsEmpleados) {
        this.smsEmpleados = smsEmpleados;
    }
    public Set<SmsVehiculo> getSmsVehiculos() {
        return this.smsVehiculos;
    }
    
    public void setSmsVehiculos(Set<SmsVehiculo> smsVehiculos) {
        this.smsVehiculos = smsVehiculos;
    }
    public Set<SmsReservacion> getSmsReservacions() {
        return this.smsReservacions;
    }
    
    public void setSmsReservacions(Set<SmsReservacion> smsReservacions) {
        this.smsReservacions = smsReservacions;
    }

    public Set<SmsLugares> getSmsLugares() {
        return smsLugares;
    }

    public void setSmsLugares(Set<SmsLugares> smsLugares) {
        this.smsLugares = smsLugares;
    }

    public SmsMercado getSmsMercado() {
        return smsMercado;
    }

    public void setSmsMercado(SmsMercado smsMercado) {
        this.smsMercado = smsMercado;
    }

    



}


