package Modelo;
// Generated 23-feb-2016 11:25:04 by Hibernate Tools 4.3.1



/**
 * SmsCostoserviciosTiempo generated by hbm2java
 */
public class SmsCostoserviciosTiempo  implements java.io.Serializable {


     private Integer idCostoServTiempo;
     private SmsServicios smsServicios;
     private int costoServicioPrecio;

    public SmsCostoserviciosTiempo() {
    }

    public SmsCostoserviciosTiempo(SmsServicios smsServicios, int costoServicioPrecio) {
       this.smsServicios = smsServicios;
       this.costoServicioPrecio = costoServicioPrecio;
    }
   
    public Integer getIdCostoServTiempo() {
        return this.idCostoServTiempo;
    }
    
    public void setIdCostoServTiempo(Integer idCostoServTiempo) {
        this.idCostoServTiempo = idCostoServTiempo;
    }
    public SmsServicios getSmsServicios() {
        return this.smsServicios;
    }
    
    public void setSmsServicios(SmsServicios smsServicios) {
        this.smsServicios = smsServicios;
    }
    public int getCostoServicioPrecio() {
        return this.costoServicioPrecio;
    }
    
    public void setCostoServicioPrecio(int costoServicioPrecio) {
        this.costoServicioPrecio = costoServicioPrecio;
    }




}


