package Modelo;
// Generated 23-feb-2016 11:25:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SmsCategoria generated by hbm2java
 */
public class SmsCategoria  implements java.io.Serializable {


     private Integer idCategoria;
     private String categoriaNombre;
     private String categoriaDescripcion;
     private Set<SmsVehiculo> smsVehiculos = new HashSet<SmsVehiculo>(0);
     private Set<SmsMercado> smsMercados = new HashSet<SmsMercado>(0);
     private Set<SmsCostosserviciosRenta> smsCostosServiciosRentas = new HashSet<SmsCostosserviciosRenta>(0);
     
     
    public SmsCategoria() {
    }
	
    public SmsCategoria(String categoriaNombre) {
        this.categoriaNombre = categoriaNombre;
    }
    public SmsCategoria(String categoriaNombre, String categoriaDescripcion, Set<SmsVehiculo> smsVehiculos, Set<SmsMercado> smsMercados, Set<SmsCostosserviciosRenta> smsCostosServiciosRenta) {
       this.categoriaNombre = categoriaNombre;
       this.categoriaDescripcion = categoriaDescripcion;
       this.smsVehiculos = smsVehiculos;
       this.smsMercados = smsMercados;
       this.smsCostosServiciosRentas = smsCostosServiciosRenta;
    }
   
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getCategoriaNombre() {
        return this.categoriaNombre;
    }
    
    public void setCategoriaNombre(String categoriaNombre) {
        this.categoriaNombre = categoriaNombre;
    }
    public String getCategoriaDescripcion() {
        return this.categoriaDescripcion;
    }
    
    public void setCategoriaDescripcion(String categoriaDescripcion) {
        this.categoriaDescripcion = categoriaDescripcion;
    }
    public Set<SmsVehiculo> getSmsVehiculos() {
        return this.smsVehiculos;
    }
    
    public void setSmsVehiculos(Set<SmsVehiculo> smsVehiculos) {
        this.smsVehiculos = smsVehiculos;
    }
    public Set<SmsMercado> getSmsMercados() {
        return this.smsMercados;
    }
    
    public void setSmsMercados(Set<SmsMercado> smsMercados) {
        this.smsMercados = smsMercados;
    }

    public Set<SmsCostosserviciosRenta> getSmsCostosServiciosRentas() {
        return this.smsCostosServiciosRentas;
    }

    public void setSmsCostosServiciosRentas(Set<SmsCostosserviciosRenta> smsCostosServiciosRenta) {
        this.smsCostosServiciosRentas = smsCostosServiciosRenta;
    }

    

    


}


