    package Modelo;
// Generated 02-mar-2016 12:47:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SmsDepartamento generated by hbm2java
 */
public class SmsDepartamento  implements java.io.Serializable {


     private Integer idDepartamento;
     private SmsPais smsPais;
     private String departamentoNombre;
     private Set<SmsCiudad> smsCiudads = new HashSet<>(0);

    public SmsDepartamento() {
        this.smsPais = new SmsPais();
    }

	
    public SmsDepartamento(SmsPais smsPais, String departamentoNombre) {
        this.smsPais = smsPais;
        this.departamentoNombre = departamentoNombre;
    }
    public SmsDepartamento(SmsPais smsPais, String departamentoNombre, Set<SmsCiudad> smsCiudads) {
       this.smsPais = smsPais;
       this.departamentoNombre = departamentoNombre;
       this.smsCiudads = smsCiudads;
    }
   
    public Integer getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public SmsPais getSmsPais() {
        return this.smsPais;
    }
    
    public void setSmsPais(SmsPais smsPais) {
        this.smsPais = smsPais;
    }
    public String getDepartamentoNombre() {
        return this.departamentoNombre;
    }
    
    public void setDepartamentoNombre(String departamentoNombre) {
        this.departamentoNombre = departamentoNombre;
    }
    public Set<SmsCiudad> getSmsCiudads() {
        return this.smsCiudads;
    }
    
    public void setSmsCiudads(Set<SmsCiudad> smsCiudads) {
        this.smsCiudads = smsCiudads;
    }




}


