package Modelo;
// Generated 23-feb-2016 11:25:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SmsEmpleado generated by hbm2java
 */
public class SmsEmpleado  implements java.io.Serializable {


     private Integer idEmpleado;
     private SmsHojavida smsHojavida;
     private SmsProveedor smsProveedor;
     private SmsUsuario smsUsuario;
     private Set<SmsCategoriasServicio> smsCategoriasServicios = new HashSet<SmsCategoriasServicio>(0);
     private Set<SmsReservacion> smsReservacions = new HashSet<SmsReservacion>(0);

    public SmsEmpleado() {
    }

	
    public SmsEmpleado(SmsProveedor smsProveedor, SmsUsuario smsUsuario) {
        this.smsProveedor = smsProveedor;
        this.smsUsuario = smsUsuario;
    }
    public SmsEmpleado(SmsHojavida smsHojavida, SmsProveedor smsProveedor, SmsUsuario smsUsuario, Set<SmsCategoriasServicio> smsCategoriasServicios, Set<SmsReservacion> smsReservacions) {
       this.smsHojavida = smsHojavida;
       this.smsProveedor = smsProveedor;
       this.smsUsuario = smsUsuario;
       this.smsCategoriasServicios = smsCategoriasServicios;
       this.smsReservacions = smsReservacions;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public SmsHojavida getSmsHojavida() {
        return this.smsHojavida;
    }
    
    public void setSmsHojavida(SmsHojavida smsHojavida) {
        this.smsHojavida = smsHojavida;
    }
    public SmsProveedor getSmsProveedor() {
        return this.smsProveedor;
    }
    
    public void setSmsProveedor(SmsProveedor smsProveedor) {
        this.smsProveedor = smsProveedor;
    }
    public SmsUsuario getSmsUsuario() {
        return this.smsUsuario;
    }
    
    public void setSmsUsuario(SmsUsuario smsUsuario) {
        this.smsUsuario = smsUsuario;
    }
    public Set<SmsCategoriasServicio> getSmsCategoriasServicios() {
        return this.smsCategoriasServicios;
    }
    
    public void setSmsCategoriasServicios(Set<SmsCategoriasServicio> smsCategoriasServicios) {
        this.smsCategoriasServicios = smsCategoriasServicios;
    }
    public Set<SmsReservacion> getSmsReservacions() {
        return this.smsReservacions;
    }
    
    public void setSmsReservacions(Set<SmsReservacion> smsReservacions) {
        this.smsReservacions = smsReservacions;
    }




}


