package Modelo;
// Generated 23-feb-2016 11:25:04 by Hibernate Tools 4.3.1



/**
 * SmsLugares generated by hbm2java
 */
public class SmsLugares  implements java.io.Serializable {


     private Integer idLugar;
     private SmsCiudad smsCiudad;
     private String lugarNombre;
     private String lugarDireccion;

    public SmsLugares() {
    }

	
    public SmsLugares(SmsCiudad smsCiudad, String lugarNombre) {
        this.smsCiudad = smsCiudad;
        this.lugarNombre = lugarNombre;
    }
    public SmsLugares(SmsCiudad smsCiudad, String lugarNombre, String lugarDireccion) {
       this.smsCiudad = smsCiudad;
       this.lugarNombre = lugarNombre;
       this.lugarDireccion = lugarDireccion;
    }
   
    public Integer getIdLugar() {
        return this.idLugar;
    }
    
    public void setIdLugar(Integer idLugar) {
        this.idLugar = idLugar;
    }
    public SmsCiudad getSmsCiudad() {
        return this.smsCiudad;
    }
    
    public void setSmsCiudad(SmsCiudad smsCiudad) {
        this.smsCiudad = smsCiudad;
    }
    public String getLugarNombre() {
        return this.lugarNombre;
    }
    
    public void setLugarNombre(String lugarNombre) {
        this.lugarNombre = lugarNombre;
    }
    public String getLugarDireccion() {
        return this.lugarDireccion;
    }
    
    public void setLugarDireccion(String lugarDireccion) {
        this.lugarDireccion = lugarDireccion;
    }




}


