package Modelo;
// Generated 02-mar-2016 12:47:17 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * SmsMercado generated by hbm2java
 */
public class SmsMercado implements java.io.Serializable {

    private Integer idMercado;
    private String mercadoNombre;
    private String mercadoDescripcion;
    private String mercadoFotoNombre;
    private String mercadoFotoRuta;
    private Set<SmsCategoriasServicio> smsCategoriasServicios = new HashSet<>();   
    private Set<SmsProveedor> smsProveedors = new HashSet<>();
    private Set<SmsCategoria> smsCategorias = new HashSet<>();

    public SmsMercado() {
        smsCategorias = new HashSet<>();
    }

    public SmsMercado(String mercadoNombre, String mercadoFotoNombre, String mercadoFotoRuta) {
        this.mercadoNombre = mercadoNombre;
        this.mercadoFotoNombre = mercadoFotoNombre;
        this.mercadoFotoRuta = mercadoFotoRuta;
    }

    public SmsMercado(String mercadoNombre, String mercadoDescripcion, String mercadoFotoNombre, String mercadoFotoRuta, Set<SmsProveedor> smsProveedors, Set<SmsCategoria> smsCategorias, Set<SmsCategoriasServicio> smsCategoriasServicios) {
        this.mercadoNombre = mercadoNombre;
        this.mercadoDescripcion = mercadoDescripcion;
        this.mercadoFotoNombre = mercadoFotoNombre;
        this.mercadoFotoRuta = mercadoFotoRuta;       
        this.smsProveedors = smsProveedors;
        this.smsCategorias = smsCategorias;
        this.smsCategoriasServicios = smsCategoriasServicios;
    }

    public Integer getIdMercado() {
        return this.idMercado;
    }

    public void setIdMercado(Integer idMercado) {
        this.idMercado = idMercado;
    }

    public String getMercadoNombre() {
        return this.mercadoNombre;
    }

    public void setMercadoNombre(String mercadoNombre) {
        this.mercadoNombre = mercadoNombre;
    }

    public String getMercadoDescripcion() {
        return this.mercadoDescripcion;
    }

    public void setMercadoDescripcion(String mercadoDescripcion) {
        this.mercadoDescripcion = mercadoDescripcion;
    }

    public String getMercadoFotoNombre() {
        return this.mercadoFotoNombre;
    }

    public void setMercadoFotoNombre(String mercadoFotoNombre) {
        this.mercadoFotoNombre = mercadoFotoNombre;
    }

    public String getMercadoFotoRuta() {
        return this.mercadoFotoRuta;
    }

    public void setMercadoFotoRuta(String mercadoFotoRuta) {
        this.mercadoFotoRuta = mercadoFotoRuta;
    }
   
    public Set<SmsProveedor> getSmsProveedors() {
        return this.smsProveedors;
    }

    public void setSmsProveedors(Set<SmsProveedor> smsProveedors) {
        this.smsProveedors = smsProveedors;
    }

    public Set<SmsCategoria> getSmsCategorias() {
        return this.smsCategorias;
    }

    public void setSmsCategorias(Set<SmsCategoria> smsCategorias) {
        this.smsCategorias = smsCategorias;
    }

    public Set<SmsCategoriasServicio> getSmsCategoriasServicios() {
        return smsCategoriasServicios;
    }

    public void setSmsCategoriasServicios(Set<SmsCategoriasServicio> smsCategoriasServicios) {
        this.smsCategoriasServicios = smsCategoriasServicios;
    }

    
}
