package Modelo;
// Generated 23-feb-2016 11:25:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SmsMercado generated by hbm2java
 */
public class SmsMercado  implements java.io.Serializable {


     private Integer idMercado;
     private String mercadoNombre;
     private String mercadoDescripcion;
     private Set<SmsServicios> smsServicioses = new HashSet<SmsServicios>(0);
     private Set<SmsProveedor> smsProveedors = new HashSet<SmsProveedor>(0);
     private Set<SmsCategoria> smsCategorias = new HashSet<SmsCategoria>(0);

    public SmsMercado() {
    }

	
    public SmsMercado(String mercadoNombre) {
        this.mercadoNombre = mercadoNombre;
    }
    public SmsMercado(String mercadoNombre, String mercadoDescripcion, Set<SmsServicios> smsServicioses, Set<SmsProveedor> smsProveedors, Set<SmsCategoria> smsCategorias) {
       this.mercadoNombre = mercadoNombre;
       this.mercadoDescripcion = mercadoDescripcion;
       this.smsServicioses = smsServicioses;
       this.smsProveedors = smsProveedors;
       this.smsCategorias = smsCategorias;
    }
   
    public Integer getIdMercado() {
        return this.idMercado;
    }
    
    public void setIdMercado(Integer idMercado) {
        this.idMercado = idMercado;
    }
    public String getMercadoNombre() {
        return this.mercadoNombre;
    }
    
    public void setMercadoNombre(String mercadoNombre) {
        this.mercadoNombre = mercadoNombre;
    }
    public String getMercadoDescripcion() {
        return this.mercadoDescripcion;
    }
    
    public void setMercadoDescripcion(String mercadoDescripcion) {
        this.mercadoDescripcion = mercadoDescripcion;
    }
    public Set<SmsServicios> getSmsServicioses() {
        return this.smsServicioses;
    }
    
    public void setSmsServicioses(Set<SmsServicios> smsServicioses) {
        this.smsServicioses = smsServicioses;
    }
    public Set<SmsProveedor> getSmsProveedors() {
        return this.smsProveedors;
    }
    
    public void setSmsProveedors(Set<SmsProveedor> smsProveedors) {
        this.smsProveedors = smsProveedors;
    }
    public Set<SmsCategoria> getSmsCategorias() {
        return this.smsCategorias;
    }
    
    public void setSmsCategorias(Set<SmsCategoria> smsCategorias) {
        this.smsCategorias = smsCategorias;
    }




}


