package Modelo;
// Generated 02-mar-2016 12:47:17 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * SmsProveedor generated by hbm2java
 */
public class SmsProveedor implements java.io.Serializable {

    private Integer idProveedor;
    private SmsUsuario smsUsuario;
    private int proveedorValorGanancia;
    private String proveedorRazonSocial;
    private String proveedorNit;
    private Set<SmsMercado> smsMercados = new HashSet<>(0);
    private Set<SmsVehiculo> smsVehiculos = new HashSet<>(0);
    private Set<SmsEmpleado> smsEmpleados = new HashSet<>(0);

    public SmsProveedor() {
        this.smsUsuario = new SmsUsuario();
    }

    public SmsProveedor(SmsUsuario smsUsuario, int proveedorValorGanancia, String proveedorRazonSocial, String proveedorNit) {
        this.smsUsuario = smsUsuario;
        this.proveedorValorGanancia = proveedorValorGanancia;
        this.proveedorRazonSocial = proveedorRazonSocial;
        this.proveedorNit = proveedorNit;
    }

    public SmsProveedor(SmsUsuario smsUsuario, int proveedorValorGanancia, Set<SmsMercado> smsMercados, Set<SmsVehiculo> smsVehiculos, Set<SmsEmpleado> smsEmpleados) {
        this.smsUsuario = smsUsuario;
        this.proveedorValorGanancia = proveedorValorGanancia;
        this.smsMercados = smsMercados;
        this.smsVehiculos = smsVehiculos;
        this.smsEmpleados = smsEmpleados;
    }

    public Integer getIdProveedor() {
        return this.idProveedor;
    }

    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }

    public SmsUsuario getSmsUsuario() {
        return this.smsUsuario;
    }

    public void setSmsUsuario(SmsUsuario smsUsuario) {
        this.smsUsuario = smsUsuario;
    }

    public int getProveedorValorGanancia() {
        return this.proveedorValorGanancia;
    }

    public void setProveedorValorGanancia(int proveedorValorGanancia) {
        this.proveedorValorGanancia = proveedorValorGanancia;
    }

    public Set<SmsMercado> getSmsMercados() {
        return this.smsMercados;
    }

    public void setSmsMercados(Set<SmsMercado> smsMercados) {
        this.smsMercados = smsMercados;
    }

    public Set<SmsVehiculo> getSmsVehiculos() {
        return this.smsVehiculos;
    }

    public void setSmsVehiculos(Set<SmsVehiculo> smsVehiculos) {
        this.smsVehiculos = smsVehiculos;
    }

    public Set<SmsEmpleado> getSmsEmpleados() {
        return this.smsEmpleados;
    }

    public void setSmsEmpleados(Set<SmsEmpleado> smsEmpleados) {
        this.smsEmpleados = smsEmpleados;
    }

    public String getProveedorRazonSocial() {
        return proveedorRazonSocial;
    }

    public void setProveedorRazonSocial(String proveedorRazonSocial) {
        this.proveedorRazonSocial = proveedorRazonSocial;
    }

    public String getProveedorNit() {
        return proveedorNit;
    }

    public void setProveedorNit(String proveedorNit) {
        this.proveedorNit = proveedorNit;
    }

}
