package Modelo;
// Generated 23-feb-2016 11:25:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SmsServicios generated by hbm2java
 */
public class SmsServicios  implements java.io.Serializable {


     private Integer idServicio;
     private SmsCategoriasServicio smsCategoriasServicio;
     private String servicioNombre;
     private String servicioDescripcion;
     private Set<SmsCostosserviciosRenta> smsCostosserviciosRentas = new HashSet<SmsCostosserviciosRenta>(0);
     private Set<SmsCostoserviciosTraslado> smsCostoserviciosTraslados = new HashSet<SmsCostoserviciosTraslado>(0);
     private Set<SmsCostoserviciosTiempo> smsCostoserviciosTiempos = new HashSet<SmsCostoserviciosTiempo>(0);
     private Set<SmsMercado> smsMercados = new HashSet<SmsMercado>(0);

    public SmsServicios() {
    }

	
    public SmsServicios(SmsCategoriasServicio smsCategoriasServicio, String servicioNombre) {
        this.smsCategoriasServicio = smsCategoriasServicio;
        this.servicioNombre = servicioNombre;
    }
    public SmsServicios(SmsCategoriasServicio smsCategoriasServicio, String servicioNombre, String servicioDescripcion, Set<SmsCostosserviciosRenta> smsCostosserviciosRentas, Set<SmsCostoserviciosTraslado> smsCostoserviciosTraslados, Set<SmsCostoserviciosTiempo> smsCostoserviciosTiempos, Set<SmsMercado> smsMercados) {
       this.smsCategoriasServicio = smsCategoriasServicio;
       this.servicioNombre = servicioNombre;
       this.servicioDescripcion = servicioDescripcion;
       this.smsCostosserviciosRentas = smsCostosserviciosRentas;
       this.smsCostoserviciosTraslados = smsCostoserviciosTraslados;
       this.smsCostoserviciosTiempos = smsCostoserviciosTiempos;
       this.smsMercados = smsMercados;
    }
   
    public Integer getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(Integer idServicio) {
        this.idServicio = idServicio;
    }
    public SmsCategoriasServicio getSmsCategoriasServicio() {
        return this.smsCategoriasServicio;
    }
    
    public void setSmsCategoriasServicio(SmsCategoriasServicio smsCategoriasServicio) {
        this.smsCategoriasServicio = smsCategoriasServicio;
    }
    public String getServicioNombre() {
        return this.servicioNombre;
    }
    
    public void setServicioNombre(String servicioNombre) {
        this.servicioNombre = servicioNombre;
    }
    public String getServicioDescripcion() {
        return this.servicioDescripcion;
    }
    
    public void setServicioDescripcion(String servicioDescripcion) {
        this.servicioDescripcion = servicioDescripcion;
    }
    public Set<SmsCostosserviciosRenta> getSmsCostosserviciosRentas() {
        return this.smsCostosserviciosRentas;
    }
    
    public void setSmsCostosserviciosRentas(Set<SmsCostosserviciosRenta> smsCostosserviciosRentas) {
        this.smsCostosserviciosRentas = smsCostosserviciosRentas;
    }
    public Set<SmsCostoserviciosTraslado> getSmsCostoserviciosTraslados() {
        return this.smsCostoserviciosTraslados;
    }
    
    public void setSmsCostoserviciosTraslados(Set<SmsCostoserviciosTraslado> smsCostoserviciosTraslados) {
        this.smsCostoserviciosTraslados = smsCostoserviciosTraslados;
    }
    public Set<SmsCostoserviciosTiempo> getSmsCostoserviciosTiempos() {
        return this.smsCostoserviciosTiempos;
    }
    
    public void setSmsCostoserviciosTiempos(Set<SmsCostoserviciosTiempo> smsCostoserviciosTiempos) {
        this.smsCostoserviciosTiempos = smsCostoserviciosTiempos;
    }
    public Set<SmsMercado> getSmsMercados() {
        return this.smsMercados;
    }
    
    public void setSmsMercados(Set<SmsMercado> smsMercados) {
        this.smsMercados = smsMercados;
    }




}


